### ISSUE TITLE
installation location guide

### ISSUE THREAD

**Issue by suljarock** [DoktorSAS/T7BOIIIMapvote#6]
No instructions where to put the mp_mapvote/zm_mapvote inside which folder

**Comment by DoktorSAS** [comment]
The organization of the page shows where the files are to be placed. 
The entire mp_mapvote/zm_mapvote folders are mods that should be compiled and used as mods.

As for the BOIII project, only the compiled file can be uploaded. Just put the file in the correct path.
In mp_mapvote it should be put in `t7-server/scripts/mp/gametypes/` while for zm_mapvote it should be put in `t7-server/scripts/zm/gametypes/ `

**Comment by abubrandino** [comment]
> The organization of the page shows where the files are to be placed. The entire mp_mapvote/zm_mapvote folders are mods that should be compiled and used as mods.
> 
> As for the BOIII project, only the compiled file can be uploaded. Just put the file in the correct path. In mp_mapvote it should be put in `t7-server/scripts/mp/gametypes/` while for zm_mapvote it should be put in `t7-server/scripts/zm/gametypes/ `

so where does mapvote.gsc go? my server is not loading it. Do you need to have sv_maprotation populated or is that to be commented out.

**Comment by DoktorSAS** [comment]
mapvote.gsc is a shared code you don't need it. As long as _clientids (in the compalied version) get loaded all should work as intended. Since i no longer mantaing the code you could run in the issue and update the code.

mapvote.gsc is just a based for both mapvote since both are based on the same logic and parameters.
You could load _clientids.gsc by it self to see if work but you have to set proper variable by recompiling the gsc or by setting them by console.

@Scattershor

**Comment by abubrandino** [comment]
> mapvote.gsc is a shared code you don't need it. As long as _clientids (in the compalied version) get loaded all should work as intended. Since i no longer mantaing the code you could run in the issue and update the code.
> 
> mapvote.gsc is just a based for both mapvote since both are based on the same logic and parameters. You could load _clientids.gsc by it self to see if work but you have to set proper variable by recompiling the gsc or by setting them by console.
> 
> [@Scattershor](https://github.com/Scattershor)

Thanks for that, but I’m gonna need more info. The thing isn’t even taking effect on the BOIII server. Also my last question about the sv_maprotation?

Can’t this just be used as is? I’ve dropped the contents of mp_mapvote into the right path as specified and added the config lines but nothing happens at the end of the match.
